import {
  LayoutDashboard,
  Wrench,
  Car,
  Users,
  FileText,
  CreditCard,
  Package,
  BarChart2,
  Settings,
  Plus,
  Search,
  Bell,
  Calendar,
  ArrowUp,
  ArrowDown,
  Check,
  ChevronRight,
  ChevronDown,
  Menu,
  Filter,
  Download,
  Printer,
  Pencil,
  Trash2,
  Eye,
  AlertTriangle,
  Clock,
  Flag,
  MoreHorizontal,
  Phone,
  Mail,
  MapPin,
  LogOut,
  ArrowLeft,
  SlidersHorizontal,
  X,
  User,
  Play,
  Save,
  EyeOff,
  type LucideProps,
} from 'lucide-react'

const MAP = {
  dashboard:    LayoutDashboard,
  wrench:       Wrench,
  car:          Car,
  users:        Users,
  doc:          FileText,
  cash:         CreditCard,
  box:          Package,
  chart:        BarChart2,
  gear:         Settings,
  plus:         Plus,
  search:       Search,
  bell:         Bell,
  calendar:     Calendar,
  'arrow-up':   ArrowUp,
  'arrow-down': ArrowDown,
  check:        Check,
  chevron:      ChevronRight,
  'chevron-down': ChevronDown,
  menu:         Menu,
  filter:       Filter,
  download:     Download,
  print:        Printer,
  edit:         Pencil,
  trash:        Trash2,
  eye:          Eye,
  alert:        AlertTriangle,
  clock:        Clock,
  flag:         Flag,
  dots:         MoreHorizontal,
  phone:        Phone,
  mail:         Mail,
  pin:          MapPin,
  logout:       LogOut,
  'arrow-left': ArrowLeft,
  sliders:      SlidersHorizontal,
  x:            X,
  user:         User,
  play:         Play,
  save:         Save,
  'eye-off':    EyeOff,
} as const

export type IconName = keyof typeof MAP

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName
}

export function Icon({ name, size = 16, strokeWidth = 1.5, ...props }: IconProps) {
  const Comp = MAP[name]
  if (!Comp) return null
  return <Comp size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />
}
